# Database connection URL, username, and password
spring.application.name=Budget Tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_tracker
spring.datasource.username=postgres
spring.datasource.password=1234567

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true